### ISSUE TITLE
Nonsense import error

### ISSUE THREAD

**Issue by fowler-mychale** [casics/nostril#15]
This is the error I receive upon running the demo. Not sure if this is python version error or not.

>  from nostril import nonsense
ImportError: cannot import name 'nonsense' from 'nostril'.

**Comment by Bishwas-py** [comment]
The same issue here. It's saying
`  File "/home/codie/Projects/websms/Environment/lib/python3.8/site-packages/nostril/core.py", line 32, in get_path
    path = __import__(package).__file__
ModuleNotFoundError: No module named 'nonsense'`

**Comment by fowler-mychale** [comment]
Needed to download from [(https://data.caltech.edu/records/1313)] then install the required python libraries:

plac>=0.9.1
tabulate>=0.7.7
humanize>=0.5.1
pytest>=3.0.5

Finally run `pip3 install git+https://github.com/casics/nostril.git` in command line.
