### ISSUE TITLE
Would you consider a license suitable for use as a library in non GPL apps?

### ISSUE THREAD

**Issue by pombredanne** [casics/nostril#9]
Hello!
I maintain https://github.com/nexB/scancode-toolkit and I have been looking for such a library which looks really nice (my use case is to remove gibberish from the strings collected from binaries). ScanCode is Apache-licensed. Would you consider some other licensing for nostril, such as any of a classpath-like exception to the GPL, the LGPL or any other permissive license?
Thank you for you kind consideration! 

NB: incidentally, scancode may be of some use in the CASICS project.

**Comment by mhucka** [comment]
Thanks for your query, and my apologies for the long delay in replying. I'm personally okay with doing that, but I need to check with my main coauthor and our institution. I will contact them this week.

**Comment by pombredanne** [comment]
@mhucka Thank you for looking in to this :bow:

**Comment by mhucka** [comment]
The institute cleared the way for a license change.  It'll be LGPL.  I'll put together a new release with the changed license. It might be a little while longer before I can get to it.

**Comment by pombredanne** [comment]
@mhucka You rock!

**Comment by pombredanne** [comment]
@mhucka gentle ping... any update?

**Comment by mhucka** [comment]
I've created a couple of milestones and have made 1.2 be the goal to switch the license. I don't think it will be too hard to do 1.2, but a workshop happening this week prevents me from doing more right now. Sorry for the continued delays...

**Comment by pombredanne** [comment]
@mhucka that's extremely gentle of you to consider this change and following through on this!

**Comment by mhucka** [comment]
This is now done!

Thank you for your patience, and also for using Nostril!

**Comment by pombredanne** [comment]
Thank you very much for this! :bowing_man:
